### ISSUE TITLE
Game crashes when I select a controller

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Stereowalker/Controller-Support-Mod#1]
I've not been able to successfully connect a controller without my game crashing. I am able to use controllable with no problem, but I really want to use yours' so I can customize my mapping and use split screen.

Thank you,
CM

OS: Linux Mint 19.3
Ram: 32gb
Launcher: ATLauncher
Mods: ControllerMod-1.15.2-1.1.0

https://paste.atlauncher.com/view/d2d0ac05

**Comment by ClaudiusMinimus** [comment]
I just installed ControllerSupport-1.15.2-1.1.2 and it still crashes.
I've tried the following controllers:

- WiiU Pro
- xbox 360 wireless
- GameSir G3f (xbox compatible) 

https://paste.atlauncher.com/view/566533ae

**Comment by Stereowalker** [comment]
Did you use Xbox 360 emulators with those controllers?

**Comment by ClaudiusMinimus** [comment]
I use xboxdvr and xwiimote, both from the Ubuntu repository. 

![joytest](https://user-images.githubusercontent.com/17887664/75077135-1ff72a00-54bf-11ea-9623-520816d67fc1.png)

**Comment by Stereowalker** [comment]
I uploaded an update, I'm pretty sure I addressed the issue so reply when you've confirmed it

**Comment by ClaudiusMinimus** [comment]
Thank you for the update!

I was able to connect the GameSir controller (controller 1). However, I was able to map the left trigger to placing a block. Also, view was uncontrollably spinning.

When I tried to connect to the WiiU Pro controller (controller 2), the game crashed.

Here is the crash report:
https://pastebin.com/VRFRTji4

And the ATLauncher client log:
https://paste.atlauncher.com/view/459cd39c

I able to connect to the Xbox 360 wireless controller (controller 3) behaved the same as the GameSir.

There were some mapping issues, but until the spinning issues are resolved, I really cannot address them.

Thank you for your efforts and I hope my feedback is helpful.

CM

PS: One last thing, all of these controllers work with the mods: Controllable and with Joy Pad Split Screen.

**Comment by Stereowalker** [comment]
After further analysis, we can classify this with a "your controller is not supported". The controller I use has 14 buttons and 6 axes, so I kinda chalked all controllers as being the same because the PS3 and Nintendo Wii U Pro controllers I use to debug use this format

**Comment by Stereowalker** [comment]
Anyway, I've changed how buttons are recognized. In about 2-3 hours from now, I'll be updating the mod. In the update you'll have to specify in the configuration file how many buttons and axes your controller has, and you'll also have to specify which of these axes is a trigger button. And also, you won't be able to see exactly what buttons are what instead of (A, B, X, Y)  you'll see (button0, button1, button2, button3). Tell me if it worked for you after the update

**Comment by ClaudiusMinimus** [comment]
It's not working at all. All inputs can only be registered as shown below
![Screenshot from 2020-02-22 18-52-56](https://user-images.githubusercontent.com/17887664/75102177-97eb5000-55a4-11ea-8077-13e878498ea2.png)

**Comment by Stereowalker** [comment]
Go to the config file and change the load map option to 'NONE'

**Comment by Stereowalker** [comment]
From there you should be able to see the exact axis that is set to RIGHT STICK LEFT'. Whatever number that when its disabled what you'll be seeing is axis_pos(some number) or axis_neg(some number). Take that number, go back to the config file and change either 'rightTrigger' to that number

**Comment by Stereowalker** [comment]
when you solve the first one, it will still occur but with a different axis. Set the second one in the 'leftTrigger'

**Comment by Stereowalker** [comment]
![SharedScreenshot3](https://user-images.githubusercontent.com/35645830/75102301-af006100-55e9-11ea-9218-c447256e3b62.jpg)

**Comment by ClaudiusMinimus** [comment]
The mappings all now work for my GameSir (Xbox compatible). The next issue is the view continuously spins clockwise.

We are getting there!

Thanks for your help!

CM

PS: Do you have a discord that we could voice chat on? This might go faster for you. I'm a retired & disabled grandpa, and have lots of time. I'm in the US, Mountain Time (UTC -7)

**Comment by Stereowalker** [comment]
Stereowalker#1806

By the way, in the update, using the same method to specify which axes were triggers, you'll also have to specify which axis is for scrolling, camera and mouse. This should get rid of the constant spinning.

**Comment by ClaudiusMinimus** [comment]
This is my controller section of the config:

```
[controller]
	#The sensitivity of the controller ingame
	#Range: 0.0 ~ 1.0
	ingameSensitivity = 0.4
	#Enable Controller Input?
	enableControllers = true
	#Allowed Values: NONE, PS3
	loadMap = "NONE"
	#Select Controller 
	# Whatever controller you choose should be your controller minus 1. So that would mean controller 1 would be 0
	#Range: 1 ~ 8
	controllerNumber = 1
	#The sensitivity of the controller in the menu
	#Range: 0.0 ~ 1.0
	menuSensitivity = 0.2
	#Define Which axis is the right trigger. Set this higher than the number of axes to disable the right trigger
	#Range: 1 ~ 50
	rightTrigger = 5
	#Define Which axis is the left trigger. Set this higher than the number of axes to disable the left trigger
	#Range: 1 ~ 50
	leftTrigger = 2
	#Invert The Y-Axis
	invertYAxis = false
```

I do not see anything indicating scrolling, camera or mouse. Please paste in the variable names, so I can make the changes. Please forgive me if I am blind.

Thank you,
CM

**Comment by Stereowalker** [comment]
is this 1.1.5?

**Comment by ClaudiusMinimus** [comment]
ATLauncher does not see your 1.1.5 update, so I just downloaded it. I'll let you know if it works.
Thanks, CM

**Comment by Stereowalker** [comment]
I solved the issue of the mouse always seemingly being clicked in 1.1.6

**Comment by ClaudiusMinimus** [comment]
Well, I've struggled to get 1.1.5 working with my xbox 360 wireless, but its sort of playable. 

I'll try 1.1.6 - I had to use my tab key a lot due to the mouse issue

Also, is there a way to do the shift-click action for quickly moving stacks or items?

**Comment by ClaudiusMinimus** [comment]
1.1.6 is much better!

Have you looked at the code for controllable and JoyModSplitScreen? Both mods properly identify the controllers and axis.

I'm willing to keep testing if you keep refining.

Keep up the good work!

CM

**Comment by Stereowalker** [comment]
As long as you're not having any issues, I can take a little break. After this issue, I've thrown away any knowledge I have about controllers and I've decided to make this a mod where you can use any controller in the world and not have issues. By the way, if you have the time, send your GameSir and Xbox 360 mappings. I want to make it easier for anyone to identify their buttons. An example would be 
button0 = A, button1 = Left Bumper, something like that

**Comment by ClaudiusMinimus** [comment]
Will do. Thanks again!

**Comment by Stereowalker** [comment]
also, add me on discord

**Comment by ClaudiusMinimus** [comment]
What if I did screenshots of the 7 config GUI's and posted them in this thread?

**Comment by Stereowalker** [comment]
that wouldn't work, because what I'm trying to do is translate the buttons for someone with your controller
