### ISSUE TITLE
Crashing when connecting to controller

### ISSUE THREAD

**Issue by JoJoNoid** [Stereowalker/Controller-Support-Mod#16]
Minecraft launches as normal (I am using Forge and Optifine by the way if that helps at all), and when I try to connect my Playstation 3 controller using a usb port, Minecraft crashes. It did not at first, showing up normally, but now anytime it is plugged in, it shows the "saving world" screen and closes. Even when just opening Minecraft when the controller is plugged in, it loads and immediately crashes.

**Comment by CW963** [comment]
Same Problem but when leaving the controller turned of I can edit a few things(but the input settings) without crashing.
