### ISSUE TITLE
Shows no main manifest attribute

### ISSUE THREAD

**Issue by EMorris71** [Stereowalker/Controller-Support-Mod#2]
File does not launch in terminal. States no main manifest. Please advise.
![Screenshot from 2020-03-29 23-05-40](https://user-images.githubusercontent.com/48297394/77871400-ff369880-7211-11ea-8a84-c51e468ef769.png)

**Comment by Stereowalker** [comment]
You're not supposed to run that command on mod files

**Comment by EMorris71** [comment]
Can you send a how to then? Thanks. 

Everett E. Morris

**Comment by Stereowalker** [comment]
If you want the mod installed, put it in your "mods" folder

**Comment by EMorris71** [comment]
Just extract it in the mods folder? Thanks. 

Everett E. Morris

**Comment by Stereowalker** [comment]
Yes just put the mod jar in your mods folder
