### ISSUE TITLE
Keybindings

### ISSUE THREAD

**Issue by Gavin456b** [Stereowalker/Controller-Support-Mod#27]
Custom controller keybindings that I set for mods do not save when the game is restarted. Also not all modded controls appear in the list all the time. Sometimes they do, sometimes they dont.

**Comment by Stereowalker** [comment]
I'll see how I can sort it out

**Comment by Stereowalker** [comment]
The 4.2.0 update should address this issue. Please can you confirm if this is the case

**Comment by TheRogueRowan** [comment]
I am using the 4.2.0 version and I have this issue as well. It doesn't save my bindings and often times, certain modded controls don't appear. I have to restart my game several times until the controls appear. The issue seems to be mainly with Quark's autowalk feature, if that makes a difference.

**Comment by Stereowalker** [comment]
Fixed in 1.18

**Comment by 8BitIce** [comment]
hi, I still have this issue in version 1.19.3-8.0.3
