### ISSUE TITLE
Controller Support has class loading errors

### ISSUE THREAD

**Issue by Azara96** [Stereowalker/Controller-Support-Mod#31]
Java.lang.NoClassDefFoundError: Com/stereowalker/unionlib/mod/UnionMod

Full crash report attatched 
[crash-2021-10-05_02.02.03-fml.txt](https://github.com/Stereowalker/Controller-Support-Mod/files/7283602/crash-2021-10-05_02.02.03-fml.txt)

**Comment by Stereowalker** [comment]
Please proceed to install the latest version of UnionLib
