### ISSUE TITLE
Many key bindings on and after v4.1.0 don't show up

### ISSUE THREAD

**Issue by pelletstove** [Stereowalker/Controller-Support-Mod#32]
Seems like after v4.1.0 many mod key bindings no longer show up in the config menu. However they all seem to show up in v4.0.3 of Controller-Support-Mod.

This seems to still be an issue even in v5.0.0

A simple test would be with a mod like Xaeros Maps. No XaerosMaps binding shows up in the Controller Menu for this mod.
https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/3475469

**Comment by Stereowalker** [comment]
Fixed 🎉🎊
