### ISSUE TITLE
Game wont launch with this mod installed.

### ISSUE THREAD

**Issue by ghost** [Stereowalker/Controller-Support-Mod#34]
The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: com/stereowalker/unionlib/mod/MinecraftMod
Exit Code: -1

Tested with just this mod and the latest version of forge and thats it.

**Comment by Stereowalker** [comment]
Please Install UNionLib

**Comment by ghost** [comment]
Alright will try that next time. Thanks.

**Comment by ghost** [comment]
Thanks this fixed the problem.
