### ISSUE TITLE
Error loading mod

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Stereowalker/Controller-Support-Mod#4]
I just downloaded your 1.16.1 mod ControllerSupport-1.16.1-2.0.0.jar and as the screenshot shows Minecraft thinks it is a 1.15.2 mod.

![Selection_035](https://user-images.githubusercontent.com/17887664/88135061-63a3ac00-cba3-11ea-9a99-91645a69b4e4.png)

Minecraft: 1.16.1
ControllerSupport-1.16.1-2.0.0.jar
Forge: 1.16.1-32.0.75
Java: 1.8.0_212

**Comment by Stereowalker** [comment]
Well, that was a mistake on my part

**Comment by Stereowalker** [comment]
Could i request your assistance with your controllers. I want to add support for a lot more controllers but the only one I have is a PS4. So could help by sending the mappings of your controllers so that i can add them to the mod?
