### ISSUE TITLE
Crash to title screen when assigning keybind. 

### ISSUE THREAD

**Issue by Dimmidice** [Stereowalker/Controller-Support-Mod#40]
Ran Minecraft with only this mod, unionlib, fabric and forgeconfigapiport. On title screen went to options, keybinds, controller. Trying to assign a keybind causes a near instant crash to title screen. Using a PS4 controller. Have tried with and without DS4windows. 

I'm using [UnionLib-1.18.1-6.2.0-Forge] & [Controller Support-1.18.1-6.1.1-Fabric]. I know they're not the latest ones, the latest ones fully crash right away for me. Which i guess is another thing altogether.

[crash-2022-03-22_23.28.04-client.txt](https://github.com/Stereowalker/Controller-Support-Mod/files/8328259/crash-2022-03-22_23.28.04-client.txt)

**Comment by Stereowalker** [comment]
It's precisely because you are not using the latest version of Controller Support-1.18.1 that the crash is occurring. 6.1.2 addresses this issue

**Comment by Dimmidice** [comment]
> It's precisely because you are not using the latest version of Controller Support-1.18.1 that the crash is occurring. 6.1.2 addresses this issue

Fair, but the newest ones crash before the game even opens. Turns out there is a crash report for it even though the game doesn't really open. 
[crash-2022-03-22_23.58.00-client.txt](https://github.com/Stereowalker/Controller-Support-Mod/files/8328343/crash-2022-03-22_23.58.00-client.txt)

Edit: Same set up as above btw. Only controller support, unionlib, fabric API, and forgeconfigapiport.

**Comment by Stereowalker** [comment]
You make a fair point too. Funny enough, I've fixed this in the 1.18.2 version

**Comment by Dimmidice** [comment]
Could i configure the keybinds on 1.18.2 and then find the config file and use the file on the 1.18.1 version? or are they different? The server i want to play on has a modpack and is on 1.18.1 so i cant really use 1.18.2 sadly.

**Comment by Stereowalker** [comment]
Yes, you can do that. I didn't change how the bindings are saved. The file you're looking for is `controlleroptions.txt` and you'd find it where the `options.txt` file is

**Comment by Stereowalker** [comment]
I've backported the mod to 1.18.1 which in turn fixes this issue. Thanks for raising it

**Comment by DailyEffortBird** [comment]
> Yes, you can do that. I didn't change how the bindings are saved. The file you're looking for is `controlleroptions.txt` and you'd find it where the `options.txt` file is



> Could i configure the keybinds on 1.18.2 and then find the config file and use the file on the 1.18.1 version? or are they different? The server i want to play on has a modpack and is on 1.18.1 so i cant really use 1.18.2 sadly.

Could you send me the config file your 1.18.2 version of the game generated?
