### ISSUE TITLE
Trying to Start Minecraft with this installed as well as Better Minecraft 1.18.2 results in a crash

### ISSUE THREAD

**Issue by Drbruhtong** [Stereowalker/Controller-Support-Mod#47]
Hi, as the title says above, the minecraft application will instantly crash upon trying to load minecraft. Since I played on consoles my whole life, and therefore computer keyboards are incredibly strange to play on, this is a big issue. Please tell me how to fix this, or patch the issue.

**Comment by Stereowalker** [comment]
I'm closing this as I've most likely fixed the issue for 1.18.2 on both Forge and Fabric
