### ISSUE TITLE
Can't open FabricMC without it crashing

### ISSUE THREAD

**Issue by BoyImYush** [Stereowalker/Controller-Support-Mod#65]
Every time I try to open the game with the Controller Support mod on, it always crashes. I've tried taking every other mod out (besides the required ones) and it still crashes. And it isn't the forgeconfigapiport or unionlib, because if i try it without the Controller Support mod, it works.

[crash-2023-10-07_08.49.01-client.txt](https://github.com/Stereowalker/Controller-Support-Mod/files/12837025/crash-2023-10-07_08.49.01-client.txt)

**Comment by BoyImYush** [comment]
it also doesn't work on forge

**Comment by 32bitx64bit** [comment]
Same issue here, I was trying to bugfix my modpack and I just couldn't figure out why controller support was crashing it.

**Comment by 32bitx64bit** [comment]
Fixed in the latest version it seems @BoyImYush , you can close the issue now

**Comment by BoyImYush** [comment]
> Fixed in the latest version it seems @BoyImYush , you can close the issue now

Yeah i saw the latest version and it's fixed now, i forgot i had this open thanks
