### ISSUE TITLE
displaying a nickname

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Stereowalker/Controller-Support-Mod#8]
hi! an xbox one controller is used. for some reason, I see my nickname in the upper-right part of the screen, and it bothers me. how can I disable this? or it would be great if you implemented the option to disable it

**Comment by Envel-Nikita-Gutsenkov** [comment]
1.15.2

**Comment by Stereowalker** [comment]
Already added in the latest version of the game
