### ISSUE TITLE
version request

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [Stereowalker/Controller-Support-Mod#9]
hi! mods are the kind of thing that the new version isn't always good at. moreover, many servers and builds are currently using 1.12.2. Can I ask you to port to this version since there are no alternatives?

**Comment by Stereowalker** [comment]
Use Tough as Nails

**Comment by Stereowalker** [comment]
@Envel-Nikita-Gutsenkov i was asleep when i suggested that. Use Joypad Mod. They seem to have stopped updating at 1.12 https://github.com/ljsimin/MinecraftJoypadSplitscreenMod
